version: 2.0
jobs:
  build:
    docker:
      - image: appirio/dx-salesforce:latest
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
